"use client"

import { motion } from "framer-motion"
import {
    Activity,
    AlertCircle,
    AlertTriangle,
    Anchor,
    Aperture,
    Archive,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    AtSign,
    Award,
    BarChart,
    BarChart2,
    Battery,
    Bell,
    BellOff,
    Bike,
    Bluetooth,
    Bold,
    Book,
    BookOpen,
    Bookmark,
    Box,
    Briefcase,
    Calendar,
    Camera,
    Cast,
    Check,
    CheckCircle,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    Clipboard,
    Clock,
    Cloud,
    CloudRain,
    CloudSnow,
    Code,
    Code2,
    Coffee,
    Command,
    Compass,
    Copy,
    CornerDownLeft,
    CornerDownRight,
    CornerUpLeft,
    CornerUpRight,
    Cpu,
    CreditCard,
    Database,
    Delete,
    Disc,
    Divide,
    DollarSign,
    Download,
    DownloadCloud,
    Dribbble,
    Edit,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FastForward,
    Feather,
    File,
    FileText,
    Film,
    Filter,
    Flag,
    Folder,
    FolderOpen,
    Gift,
    Github,
    Gitlab,
    Globe,
    Grid,
    HardDrive,
    Heart,
    HelpCircle,
    Home,
    Image,
    Inbox,
    Info,
    Instagram,
    Italic,
    Layers,
    Layout,
    LifeBuoy,
    Link,
    Link2,
    List,
    Loader,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Maximize,
    Maximize2,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    MicOff,
    Minimize,
    Minimize2,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    Music,
    Navigation,
    Navigation2,
    Octagon,
    Package,
    Paperclip,
    Pause,
    PauseCircle,
    PenTool,
    Percent,
    Phone,
    PhoneCall,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    PieChart,
    Pin,
    Pipette,
    Plane,
    Play,
    PlayCircle,
    Plus,
    PlusCircle,
    PlusSquare,
    Pocket,
    Power,
    Printer,
    Radio,
    RefreshCw,
    Repeat,
    Rewind,
    RotateCcw,
    RotateCw,
    Rss,
    Save,
    Scissors,
    Search,
    Send,
    Settings,
    Share,
    Share2,
    Shield,
    ShoppingBag,
    ShoppingCart,
    Shuffle,
    Sidebar,
    SkipBack,
    SkipForward,
    Slack,
    Slash,
    Sliders,
    Smartphone,
    Smile,
    Speaker,
    Square,
    Star,
    Sun,
    Sunrise,
    Sunset,
    Tablet,
    Tag,
    Target,
    Terminal,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    ToggleLeft,
    ToggleRight,
    Trash,
    Trash2,
    TrendingDown,
    TrendingUp,
    Triangle,
    Truck,
    Tv,
    Twitch,
    Twitter,
    Type,
    Underline,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserMinus,
    UserPlus,
    Users,
    Video,
    VideoOff,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Watch,
    Wifi,
    WifiOff,
    Wind,
    X,
    XCircle,
    XSquare,
    Youtube,
    Zap,
    ZapOff
} from "lucide-react"

const iconVariants = {
    hidden: { opacity: 0, scale: 0.8 },
    visible: { opacity: 1, scale: 1 },
}

const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
        opacity: 1,
        transition: {
            staggerChildren: 0.05,
            delayChildren: 0.2,
        },
    },
}

const icons = [
    Activity, AlertCircle, AlertTriangle, Anchor, Aperture, Archive,
    ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AtSign, Award, BarChart, BarChart2,
    Battery, Bell, BellOff, Bike, Bluetooth, Bold, Book, BookOpen,
    Bookmark, Box, Briefcase, Calendar, Camera, Cast, Check, CheckCircle, CheckSquare,
    ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, Clipboard, Clock,
    Cloud, CloudRain, CloudSnow, Code, Code2, Coffee, Command, Compass, Copy,
    CornerDownLeft, CornerDownRight, CornerUpLeft, CornerUpRight, Cpu, CreditCard,
    Database, Delete, Disc, Divide, DollarSign, Download, DownloadCloud, Dribbble,
    Edit, Edit2, Edit3, ExternalLink, Eye, EyeOff, Facebook, FastForward, Feather,
    File, FileText, Film, Filter, Flag, Folder, FolderOpen, Gift, Github, Gitlab,
    Globe, Grid, HardDrive, Heart, HelpCircle, Home, Image, Inbox, Info, Instagram,
    Italic, Layers, Layout, LifeBuoy, Link, Link2, List, Loader, Lock, LogIn,
    LogOut, Mail, Map, MapPin, Maximize, Maximize2, Menu, MessageCircle, MessageSquare,
    Mic, MicOff, Minimize, Minimize2, Minus, MinusCircle, MinusSquare, Monitor, Moon,
    MoreHorizontal, MoreVertical, Move, Music, Navigation, Navigation2, Octagon,
    Package, Paperclip, Pause, PauseCircle, PenTool, Percent, Phone, PhoneCall,
    PhoneForwarded, PhoneIncoming, PhoneMissed, PhoneOff, PieChart, Pin, Pipette,
    Plane, Play, PlayCircle, Plus, PlusCircle, PlusSquare, Pocket, Power, Printer,
    Radio, RefreshCw, Repeat, Rewind, RotateCcw, RotateCw, Rss, Save, Scissors,
    Search, Send, Settings, Share, Share2, Shield, ShoppingBag, ShoppingCart, Shuffle,
    Sidebar, SkipBack, SkipForward, Slack, Slash, Sliders, Smartphone, Smile,
    Speaker, Square, Star, Sun, Sunrise, Sunset, Tablet, Tag, Target, Terminal,
    Thermometer, ThumbsDown, ThumbsUp, ToggleLeft, ToggleRight, Trash,
    Trash2, TrendingDown, TrendingUp, Triangle, Truck, Tv, Twitch, Twitter, Type,
    Underline, Upload, UploadCloud, User, UserCheck, UserMinus, UserPlus, Users,
    Video, VideoOff, Volume, Volume1, Volume2, VolumeX, Watch, Wifi, WifiOff,
    Wind, X, XCircle, XSquare, Youtube, Zap, ZapOff
]

export function Icons() {
    return (
        <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="grid grid-cols-4 md:grid-cols-6 lg:grid-cols-8 gap-4 p-4"
        >
            {icons.map((Icon, index) => (
                <motion.div
                    key={index}
                    variants={iconVariants}
                    className="flex items-center justify-center w-12 h-12 bg-muted rounded-lg hover:bg-accent transition-colors"
                >
                    <Icon className="w-6 h-6 text-muted-foreground" />
                </motion.div>
            ))}
        </motion.div>
    )
}
